### ISSUE TITLE
Resolve parser defects 2: tests from glslang

### ISSUE THREAD

**Issue by automaticp** [nolanderc/glsl_analyzer#21]
Ran v1.1.2 through a handpicked subset of [tests for glslang](https://github.com/KhronosGroup/glslang/tree/main/Test). Picked out the files that are: 
- GLSL (mostly OpenGL, has some minimal Vulkan dialect, but skipped `spv.*` files for now);
- not ES (removed es keywords in some files that are otherwise valid core);
- do not test for failure or errors, but are expected to compile (commented out some expected-to-fail lines as well). Was only looking for cases where the code is well-formed, but the parser erroneously disagrees.

Don't have time right now to condense to snippets and minimal repros, but I have this output that points to the problematic files:

```
FAILED(001): comment.frag:11:7: expected ;
FAILED(002): constantUnaryConversion.comp:26:5: expected ,
FAILED(003): constFoldIntMin.frag:6:23: expected ,
FAILED(004): decls.frag:41:17: expected )
FAILED(005): numeral.frag:78:20: expected ,
FAILED(006): preprocessor.edge_cases.vert:3:17: expected a declaration
FAILED(007): preprocessor.function_macro.vert:9:26: expected ;
FAILED(008): stringToDouble.vert:110:36: expected ,
FAILED(009): tokenPaste.vert:18:14: expected ;

FAILED 9 out of 161 files.
```

Just look for the files with the same names at the link above, the `line:column` points to the first error occurrence. 

- `(001)`: Does not escape a newline in a single-line comment;
- `(002)`: ??? I'd be confused too :woozy_face:, maybe the previous declaration already broke it?
- `(003)`: Non-standard integer suffix as part of the extension;
- `(004)`: Declaration in the `while` condition. [Seems to be legal](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.html#shading-language-grammar) (see *condition* and *iteration_statement* rules);
- `(005)`: Floating-point suffix `Lf`. Spec only allows `f, F, lf, LF`, but it's not marked as ERROR in the file. Not sure who's right;
- `(006)`: Multiline comment in a `#define` :vomiting_face:;
- `(007)`: Newline escape in a macro definition;
- `(008)`: Same as `(005)`;
- `(009)`: Declaration substituted through a macro. If the parser does not keep track of macros, then, well...

Overall pretty clean, mostly newline escapes and `(004)` are relevant.

**Comment by automaticp** [comment]
Also should these files be pulled into the `samples/` for future regression tests, etc.?

**Comment by automaticp** [comment]
Actually cannot figure out the license for the test glsl code in glslang. Uh...

**Comment by nolanderc** [comment]
Oh wow! Nice work!

There will certainly be some issues relates to macros as we don’t expand them, so unless they look like regular function calls/identifiers stuff will go wrong.

Newline escapes is also something I have mostly ignored since it’s rarely used, but I guess macros is an obvious exception.

It would probably be nice to have these somewhere, so feel free to add them! So far I mostly use samples for interactive debugging, but having a more structured approach would be nice.

**Comment by nolanderc** [comment]
> Actually cannot figure out the license for the test glsl code in glslang. Uh...

An alternative is just to extract a minimal example and commit that, it’s what I’ve done so far

**Comment by automaticp** [comment]
Alright, I'll try to figure something out over the weekend

**Comment by nolanderc** [comment]
Most of these are fixedin #31.

See #30 for the remaining issue surrounding macros (tokenPaste.vert).
