### ISSUE TITLE
Variable declarations in global scope suggest to auto-complete themselves

### ISSUE THREAD

**Issue by automaticp** [nolanderc/glsl_analyzer#23]
Declaring a variable in local scope does not produce suggestions:

![image](https://github.com/nolanderc/glsl_analyzer/assets/83063079/2cb9dace-46ef-4eab-96cb-4a304a32b7bd)

This is expected.

Variable declarations in global scope suggest to autocomplete to themselves:

![image](https://github.com/nolanderc/glsl_analyzer/assets/83063079/5a69244d-aadb-45a7-bcf8-4aba979fb1bc)

It will keep suggesting itself as you type it out further. If the variable is declared for the first time, however, the self-suggestion does not appear until all other options have been rejected:

![image](https://github.com/nolanderc/glsl_analyzer/assets/83063079/706d13d2-6045-4c75-9d48-e01a7b17ef3a)

Not sure how much of an effort it would be to fix this, but since it works for locals, I'm hoping it's a simple change. Ideally, suggestions should not appear at all in declarations when typing them out, but it might be harder to get that right in the global scope.

**Comment by nolanderc** [comment]
Should be working in v1.1.3.

This behaviour is there to allow for hover information on declarations themselves, which uses the same logic as completions.

There could still be false positives with forward declarations, but that will require a new name-resolution algorithm.
