### ISSUE TITLE
Add comprehensive testing for hover and autocomplete

### ISSUE THREAD

**Issue by automaticp** [nolanderc/glsl_analyzer#26]
These features are hard to get right, and we have seen some edge cases pop up over the last week.

As far as I understood, the current way of supplying the hover info by walking the parse-tree up is never going to be perfect, so the tests have to be permissive and be more of a warning of where the current approach is not up to the task. Still, seeing the overall picture should be highly beneficial, and should help both make compromises with the current design, as well as assist in integrating the (foreshadowed) type/semantic analysis.

So yeah we need tests.

**Comment by automaticp** [comment]
I'm thinking of cooking up some kind of ubershader that exercises as many glsl features as possible, and then just "hovering" all over it in tests for a start. Genius, I know.

@nolanderc, thoughts, ideas or even just a "go ahead" are welcome!

**Comment by nolanderc** [comment]
One issue with larger test samples is that errors further up in the file may cause more errors further down, so while an uber-shader may be good to find bugs, breaking it down into smaller minimal examples which isolate the bug is still a good idea. Other than that, go right ahead 😄

**Comment by automaticp** [comment]
Alright, I've played around for a bit with [pytest-lsp](https://pypi.org/project/pytest-lsp/) and it seems quite decent for testing lsp-servers. Please, take a look at it and tell me if that's okay with you. I'm thinking of making a small wrapper around it to provide a more-or-less straightforward interface similar to the following: 

```python3
with client.open_file(path) as file:
    file.expect_hover((24, 11), "const vec4")
    file.expect_hover((102, 13), "layout(location = 1) in vec2")
    file.expect_completion_contains((42, 10), ["gl_FragCoord", "gl_FragDepth"])
    # etc...
```
then stamping out a bunch of tests like this and running them with pytest as part of `run-all-tests.sh`.

> One issue with larger test samples is that errors further up in the file may cause more errors further down, so while an uber-shader may be good to find bugs, breaking it down into smaller minimal examples which isolate the bug is still a good idea. 

That's a good point. I'll probably start from smaller samples that are well-formed anyways. Then we will see how it behaves under errors.

**Comment by nolanderc** [comment]
Oh that’s cool! That would be great! Thinking about it, maybe the `*.sh` scripts should be converted to python as well, so that they are easliy run under Windows?

Regarding uber-shaders: I would like the parser to be resilient enough to handle errors better, so we could have a few tests like that.

**Comment by automaticp** [comment]
Well..., I just spent 4 hours trying to run something similar to subcases in pytest until I realized that you functionally just cannot do that without an extension. My head hurts. 

In the end, I couldn't get it too look anything close to the declarative style I wanted (pytest is truly an "Inversion of Control Testing Framework"), but at least with subtests we can specify input/expected_output as data upfront and let the ugly parts do the work. [You can take a look](https://github.com/automaticp/glsl_analyzer/blob/782ac9f8f7e2ef6d74e3faaef4d3f9021e7a9fb7/tests/test_lsp.py) at how it is right now, I'll probably undo that commit later to rework it though.


> Thinking about it, maybe the *.sh scripts should be converted to python as well

Should not be a problem, yeah.

> Regarding uber-shaders: I would like the parser to be resilient enough to handle errors better, so we could have a few tests like that.

I realized one thing: if we specify the hover/completion cursor as absolute line/column values, then the ubershader becomes problematic for maintainig it if it ever comes to adding more code to it, since that breaks positions for the tested lines that follow the new ones. It's kinda has... O(n) complexity maintenance cost :weary:.

**Comment by nolanderc** [comment]
> [You can take a look](https://github.com/automaticp/glsl_analyzer/blob/782ac9f8f7e2ef6d74e3faaef4d3f9021e7a9fb7/tests/test_lsp.py) at how it is right now, I'll probably undo that commit later to rework it though.

It took some time to grok, but it doesn't look too bad actually!

I wonder, could you programatically pass in new paths/hovers? For example, the ideal would be something like the following:

```python
expect_responses(
    paths={ "basic.vert": ".../basic.vert" },
    hovers={ "basic.vert": [((12, 34), "const vec4"), ...] },
)
expect_responses(
    paths={ "complicated.vert": ".../complicated.vert" },
    hovers={ "complicated.vert": [((42, 17), "const WhateverStruct[2]"), ...] },
)
```

> I realized one thing: if we specify the hover/completion cursor as absolute line/column values, then the ubershader becomes problematic for maintainig it if it ever comes to adding more code to it, since that breaks positions for the tested lines that follow the new ones. It's kinda has... O(n) complexity maintenance cost 😩.

Yeah that could be a problem... However, we could do something similar to what I did [here](https://github.com/automaticp/glsl_analyzer/blob/5a6fa2456e9e8447aad4a56f03aa9cf7345e359b/src/analysis.zig#L557-L562). Essentially, we add some "marker" comments to point to a specific location, and then check that the error is reasonably close (that is, the error should be "connected" to the marker comment by whitespace, if that makes sense). You can then match the errors to the contents of the markers, and ensure that the correct errors end up with the expected markers, or something like that.

**Comment by nolanderc** [comment]
Usage with markers may look something like:

```python
expect_responses(
    paths={ "basic.vert": ".../basic.vert" },
    hovers={ "basic.vert": [("/* here */", "const vec4"), ...] },
)
```

with a `basic.vert`:
```glsl
const vec4 color = vec4(1,0,0,1);

void main() {
    /* here */color;
}
```

Although I now realize that this limits where we can hover, as we cannot put a comment in the middle of an identifier.

**Comment by nolanderc** [comment]
Hmm, yeah... In an ideal world, the parser shouldn't propagate syntax errors too far down the file, so maybe ubershaders are the wrong approach after all. What we really should be testing for is that parse errors are kept close to the actual syntax error:
```glsl
const int foo = /* oops, missing value.. */
// <no errors past this line>
const int bar = 124;
```

**Comment by automaticp** [comment]
I'm wondering, what is the expected behavior when hovered at the end of an identifier? Right now it does not show anything, is that intentional and should we go forward with that assumption?

![image](https://github.com/nolanderc/glsl_analyzer/assets/83063079/822e25a4-dee2-40b4-80eb-4985531b97e3)


For reference, clangd (C/C++ language server) shows the identifier info if the identifier is alone:

(couldn't capture the caret, but it's at the end)
![image](https://github.com/nolanderc/glsl_analyzer/assets/83063079/97d39507-c423-4a40-9c79-08e4d0fb5a0e)


but switches to showing the info of a field if it's present:

![image](https://github.com/nolanderc/glsl_analyzer/assets/83063079/51a27ddf-bf42-42a6-b1cd-5257ccef74d8)

I'm hovering by placing the caret at the position and pressing the hover button, so I expect the closest identifier to be highlighted, but clangd's approach seems to be more intuitive if you're actually hovering with the mouse cursor, since you look at characters and not spaces between them.

I'm asking mostly so that I would know what to expect in tests, should it stay `None` when the caret is past the end?

**Comment by automaticp** [comment]
> In an ideal world, the parser shouldn't propagate syntax errors too far down the file, so maybe ubershaders are the wrong approach after all. What we really should be testing for is that parse errors are kept close to the actual syntax error:

Hopefully, we'll tackle that in "step 2" of parser testing.
