### ISSUE TITLE
Setup with neovim

### ISSUE THREAD

**Issue by Niwol** [nolanderc/glsl_analyzer#51]
Hello, I am struggling with setting up glsl_analyzer with neovim.
I've followed the instructions in the README.md:
I installed it via source code and put the build directory in the PATH and this seems to work

![Screenshot from 2023-12-28 09-44-00](https://github.com/nolanderc/glsl_analyzer/assets/56219632/335ee5c5-6bdb-4e74-88db-ff68b79a2501)

I then added this in my neovim config:
```
-- glsl
require'lspconfig'.glsl_analyzer.setup{
    on_attach = function()
        print("attached")
    end
}
```

However this does not print "attached" when i open an .vert or .frag file and there is no syntax highlight or completion proposition other than from the buffer.

![Screenshot from 2023-12-28 09-38-16](https://github.com/nolanderc/glsl_analyzer/assets/56219632/c4d2531e-2a4e-438b-997a-eab6f02569b6)

Does anyone know a solution to my problem ?
I am using:
Ubuntu 22.04.3 LTS
neovim: NVIM v0.10.0-dev-1412+g1094d0c0d

**Comment by nolanderc** [comment]
Hi!

This is probably due to missing a `filetype` for glsl. Try either running `set filetype=glsl` or install this syntax highlighting plugin which should to this automatically: https://github.com/tikhomirov/vim-glsl.

If this works for you, we may want to add a note in the README.

**Comment by Niwol** [comment]
It works for me with `set filetype=glsl`. Thank you.

**Comment by biskwikman** [comment]
Hello, just wanted to say that I had the same issue and it was fixed with the vim-glsl plugin recommended above. Using lazy nvim.
