### ISSUE TITLE
glsl_analyzer does not compile with Zig 0.12.0

### ISSUE THREAD

**Issue by wr7** [nolanderc/glsl_analyzer#55]
Zig 0.12.0 was just released, but compiling glsl_analyzer with it causes several errors.

I tried fixing some of them, but I don't really have enough time or experience with Zig to completely fix everything. Here's a diff of what I've done so far if you want to use it as a starting point:

[zig_12_compatibility.PATCH](https://github.com/nolanderc/glsl_analyzer/files/15052526/zig_12_compatibility.PATCH)

**Comment by nolanderc** [comment]
Thanks, I’ll take a look tomorrow if I find the time :)
