### ISSUE TITLE
Windows/Neovim Segmentation Fault

### ISSUE THREAD

**Issue by msagca** [nolanderc/glsl_analyzer#62]
The language server didn't seem to work inside my neovim, so I tried to test the binary directly by providing a file with the `--parse-file` option and it caused segmentation fault. Both the binary provided here and that built from source (with Zig 0.12) have the same problem. This looks like an issue with Zig, but I'm not sure.

```powershell
Segmentation fault at address 0x16424d3008d
/opt/hostedtoolcache/zig/0.12.0/x64/lib/std/fs/Dir.zig:800:56: 0x6c1f6a in openFile (glsl_analyzer.exe.obj)      
/opt/hostedtoolcache/zig/0.12.0/x64/lib/std/fs/Dir.zig:1873:37: 0x6c219b in readFileAlloc (glsl_analyzer.exe.obj)
/home/runner/work/glsl_analyzer/glsl_analyzer/src/main.zig:55:50: 0x6e79e7 in main (glsl_analyzer.exe.obj)       
/opt/hostedtoolcache/zig/0.12.0/x64/lib/std/start.zig:484:75: 0x6eee66 in main (glsl_analyzer.exe.obj)
/opt/hostedtoolcache/zig/0.12.0/x64/lib/libc/mingw/crt/crtexe.c:267:0: 0x74e515 in __tmainCRTStartup (crt2.obj)  
/opt/hostedtoolcache/zig/0.12.0/x64/lib/libc/mingw/crt/crtexe.c:188:0: 0x74e565 in mainCRTStartup (crt2.obj)     
???:?:?: 0x7ff8e5907343 in ??? (KERNEL32.DLL)
???:?:?: 0x7ff8e78fcc90 in ??? (ntdll.dll)
```

OS info:

```
Edition: Windows 10 Home
Version: 22H2
OS build: 19045.4529
```

**Comment by nolanderc** [comment]
Agreed, this looks like a Zig bug. Take a look at v1.5.0, which uses Zig 0.13.0, and see if that fixes your issue.

**Comment by msagca** [comment]
Unfortunately, I still get the same error. The Linux executable works fine inside WSL though.

**Comment by msagca** [comment]
I gave it another try today and the language server works fine, closing the issue now... Thanks.
