### ISSUE TITLE
glsl_analyzer command not working

### ISSUE THREAD

**Issue by lzned** [nolanderc/glsl_analyzer#71]
I'm on windows and I've added the `glsl_analyzer/bin` directory to my path. I tried to run `glsl_analyzer` from the command line, and nothing happened. The terminal gave me an error saying that it couldn't find the command. Any idea on what's happening.

**Comment by nolanderc** [comment]
On windows, you may have to restart your application, or try logging in and out, for any changes to `PATH` to take effect.
