### ISSUE TITLE
Strange formatter behavior

### ISSUE THREAD

**Issue by gustafla** [nolanderc/glsl_analyzer#73]
I'm sorry, I haven't analyzed this bug at all, but I think it's still worth reporting.

This reproducer:
```
void main() {
    float sample = texelFetch(u_FontSampler, frag_coord, 0).r;
    FragColor = vec4(vec3(1.), sample);
}
```
Gets formatted to:
```
void main() {
    float
    sample = texelFetch(u_FontSampler, frag_coord, 0). r;
FragColor = vec4(vec3(1.), sample);
}
```

**Comment by nolanderc** [comment]
`sample` seems to be a keyword in GLSL, so the variable declaration isn’t parsed correctly as there is no valid variable name. It should be more obvious if #63 is fixed.
